blank_issues_enabled: false

contact_links:
  - name: Ask a question
    url: https://github.com/getkiosk/support/discussions/new?category=q-a
    about: Ask the community for help

  - name: Request a feature
    url: https://github.com/getkiosk/support/discussions/new?category=ideas
    about: Share ideas for new features

  - name: Report a bug
    url: https://github.com/getkiosk/support/issues/new
    about: Report a reproducable bug
